baseURL = "http://example.org/"
languageCode = "en-zh"
title = "HaHa....Blog"
theme = "ezhil"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/Adherentman"

[taxonomies]
   tag = "tags"